# Generated by Django 4.0.1 on 2022-02-24 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.CharField(max_length=50)),
                ('tmdb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='promocodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, null=True)),
                ('coupen_offer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='screens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=20)),
                ('g_r_no', models.IntegerField(default=False)),
                ('g_c_no', models.IntegerField(default=False)),
                ('g_price', models.IntegerField(default=False)),
                ('sp_r_no', models.IntegerField(default=False)),
                ('sp_c_no', models.IntegerField(default=False)),
                ('sp_price', models.IntegerField(default=False)),
                ('s_r_no', models.IntegerField(default=False)),
                ('s_c_no', models.IntegerField(default=False)),
                ('s_price', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('exp_date', models.DateField(default='22-02-2000')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreArea.movies')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreArea.screens')),
            ],
        ),
        migrations.CreateModel(
            name='theatres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('theatre_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('location_url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='used_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreArea.promocodes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_uid', models.CharField(default=False, max_length=500)),
                ('total_price', models.IntegerField(null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreArea.shows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='screens',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreArea.theatres'),
        ),
        migrations.CreateModel(
            name='booked_seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_user', models.CharField(max_length=250, null=True)),
                ('seat_no', models.CharField(default=False, max_length=20)),
                ('seat_category', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatreArea.shows')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theatreArea.tickets')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
