# Generated by Django 4.0.1 on 2022-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreArea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date',
            field=models.DateField(default='2000-02-22'),
        ),
    ]
