# Generated by Django 4.0.1 on 2022-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreArea', '0002_tickets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
