# Generated by Django 4.0.1 on 2022-03-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatreArea', '0003_alter_tickets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatres',
            name='acrtive',
            field=models.BooleanField(default='True'),
        ),
    ]
