# Generated by Django 4.0.1 on 2022-03-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatreArea', '0004_theatres_acrtive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatres',
            old_name='acrtive',
            new_name='active',
        ),
    ]
